# Generated by Django 4.2 on 2023-04-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
